buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'

version = '1.0.0'
group = 'cc.cassian.clickthrough'
archivesBaseName = 'clickthrough-forge-1.16.5'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: 'official', version: '1.16.5'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                clickthrough {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url 'https://repo.spongepowered.org/maven' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.16.5-36.2.39'
}

jar {
    manifest {
        attributes([
            "Specification-Title": "clickthrough",
            "Specification-Vendor": "cassiancc",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor": "cassiancc",
            "MixinConfigs": "clickthrough.mixins.json"
        ])
    }
}
